# Generated by Django 5.1.7 on 2025-03-20 12:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('github_repos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('pushed_at', models.DateTimeField(blank=True, null=True)),
                ('modified_files', models.JSONField(blank=True, null=True)),
                ('author_name', models.CharField(blank=True, max_length=255, null=True)),
                ('author_email', models.CharField(blank=True, max_length=255, null=True)),
                ('author_username', models.CharField(blank=True, max_length=255, null=True)),
                ('repo_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commit_repo_name', to='github_repos.githubrepo')),
            ],
        ),
    ]
