# Generated by Django 5.1.7 on 2025-03-21 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_branches', '0001_initial'),
        ('github_commits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commit',
            name='repo_name',
        ),
        migrations.AddField(
            model_name='commit',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commit_branch_name', to='github_branches.branch'),
        ),
    ]
