# Generated by Django 5.1.7 on 2025-03-21 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_branches', '0002_alter_branch_repo'),
        ('github_commits', '0002_remove_commit_repo_name_commit_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='github_branches.branch'),
        ),
    ]
