# Generated by Django 5.1.7 on 2025-03-21 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_branches', '0001_initial'),
        ('github_repos', '0005_alter_githubrepo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='repo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='github_repos.githubrepo'),
        ),
    ]
