# Generated by Django 5.1.7 on 2025-03-20 12:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_repos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubrepo',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='githubrepo',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
