# Generated by Django 5.1.7 on 2025-03-21 06:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_repos', '0004_alter_githubrepo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubrepo',
            name='id',
            field=models.BigIntegerField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
