# Generated by Django 5.1.7 on 2025-03-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_repos', '0005_alter_githubrepo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubrepo',
            name='main_branch',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
