# Generated by Django 5.1.7 on 2025-03-25 09:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('github_branches', '0001_initial'),
        ('github_repos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField(blank=True, null=True)),
                ('state', models.CharField(max_length=50)),
                ('base_branch', models.CharField(max_length=50)),
                ('head_branch', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=255)),
                ('html_url', models.CharField(max_length=255)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('commits', models.IntegerField(blank=True, null=True)),
                ('additions', models.IntegerField(blank=True, null=True)),
                ('deletions', models.IntegerField(blank=True, null=True)),
                ('changed_files', models.IntegerField(blank=True, null=True)),
                ('user', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('merged_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_request_branch', to='github_branches.branch')),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to='github_repos.githubrepo')),
            ],
        ),
    ]
