# Generated by Django 5.1.7 on 2025-03-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_pull_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
