# Generated by Django 5.1.7 on 2025-03-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_pull_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pullrequest',
            name='html_url',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pullrequest',
            name='url',
            field=models.URLField(max_length=255),
        ),
    ]
