# Generated by Django 5.1.7 on 2025-03-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_pull_requests', '0003_pullrequest_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='additions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='base_branch',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='changed_files',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='commits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='deletions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='head_branch',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='html_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='merged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
